<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close tcb-local-vars-root" data-css="tve-u-0620b8f4fda077" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__" data-float="1" data-tcb_hover_state_parent="" style=""><svg class="tcb-icon" viewBox="0 0 24 24" data-id="icon-close-duotone" data-name="" style=""><path fill="none" d="M0 0h24v24H0V0z"></path><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"></path></svg></div>
<div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve-elem-default-pad" data-css="tve-u-1620b8f4fda0ba" style="">
	<div class="tve-content-box-background" style="" data-css="tve-u-2620b8f4fda0f9"></div>
	<div class="tve-cb" style="" data-css="tve-u-3620b8f4fda13b"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-4620b8f4fda17f" style=""><p style="" data-css="tve-u-5620b8f4fda1bf">Get a <strong>10%</strong> discount</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-6620b8f4fda1fd" style=""><p data-css="tve-u-7620b8f4fda23b" style="">Subscribe today and get a special gift, just for you!</p></div><div class="thrv_wrapper thrv_lead_generation tve-lead-generation-template tcb-local-vars-root tve-color-set tcb-file-style-applied" data-connection="api" id="lg-kz8c0yse" data-templateconfig="{&quot;checkbox&quot;:{&quot;option&quot;:{&quot;data-value&quot;:&quot;style-2&quot;}},&quot;radio&quot;:{&quot;option&quot;:{&quot;data-value&quot;:&quot;style-1&quot;}},&quot;select&quot;:{&quot;_class&quot;:&quot;&quot;,&quot;data-show-placeholder&quot;:&quot;1&quot;,&quot;data-style&quot;:&quot;style-1&quot;,&quot;data-icon&quot;:&quot;style_1&quot;}}" data-css="tve-u-8620b8f4fda279" tcb-template-name="Opt-in Form 01" tcb-template-id="61061" data-keep-css_id="1" style="" data-element-name="Form" data-settings-id="tve-form-17ebfad5eae" data-form-settings="__TCB_FORM__{&quot;v&quot;:1,&quot;apis&quot;:{},&quot;extra&quot;:{},&quot;captcha&quot;:0,&quot;custom_tags&quot;:{},&quot;form_identifier&quot;:&quot;lightbox-form-pf16q2&quot;}__TCB_FORM__"><div class="thrive-colors-palette-config" style="display: none !important">__CONFIG_colors_palette__{"active_palette":0,"config":{"colors":{"f8a6d":{"name":"Main Accent","parent":-1}},"gradients":[]},"palettes":[{"name":"Default","value":{"colors":{"f8a6d":{"val":"rgb(195, 104, 83)","hsl":{"h":11,"s":0.4828,"l":0.5451,"a":1}}},"gradients":[]},"original":{"colors":{"f8a6d":{"val":"rgb(47, 138, 229)","hsl":{"h":210,"s":0.77,"l":0.54,"a":1}}},"gradients":[]}}]}__CONFIG_colors_palette__</div><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
	<div class="thrv_lead_generation_container tve_clearfix">
		<form action="#" method="post" novalidate="novalidate" autocomplete="new-password">
			<div class="tve_lead_generated_inputs_container tve_clearfix">
				<div class="tve_lg_input_container tve_lg_input tve_lg_regular_input tcb-plain-text tcb-no-clone" data-selector="#lg-kz8c0yse .tve_lg_regular_input:not(.tcb-excluded-from-group-item)" data-css="tve-u-9620b8f4fda2b9" data-label="tve-lg-172a8ef6ffa" style="--tve-font-size:14px;" data-tcb_hover_state_parent="">
					<input class="tcb-plain-text" type="text" data-field="name" name="name" placeholder="Name" data-placeholder="Name" style="--background-image:linear-gradient(rgba(0, 0, 0, 0.04), rgba(0, 0, 0, 0.04))  !important; --background-size:auto  !important; --background-position:0% 0%  !important; --background-attachment:scroll  !important; --background-repeat:repeat  !important;" data-required="0" data-validation="">
				</div><div class="tve_lg_input_container tve_lg_input tve_lg_regular_input tcb-plain-text tcb-no-clone tcb-no-delete" data-selector="#lg-kz8c0yse .tve_lg_regular_input:not(.tcb-excluded-from-group-item)" data-css="tve-u-10620b8f4fda2f8" data-label="tve-lg-17313d257ed" style="--tve-font-size:14px;" data-tcb_hover_state_parent="">
					<input class="tcb-plain-text" type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" style="">
				</div>
				
				<div class="thrv_wrapper tve-form-button tcb-local-vars-root tcb-with-icon tve-color-set tcb-flip" data-tcb_hover_state_parent="" data-selector="#lg-kz8c0yse .tve-form-button" data-button-style="btn-tpl-58420" style=""><div class="thrive-colors-palette-config" style="display: none !important">__CONFIG_colors_palette__{"active_palette":0,"config":{"colors":{"37fed":{"name":"Main Accent","parent":-1}},"gradients":[]},"palettes":[{"name":"Default Palette","value":{"colors":{"37fed":{"val":"rgb(195, 104, 83)","hsl":{"h":11,"s":0.4828,"l":0.5451,"a":1}}},"gradients":[]},"original":{"colors":{"37fed":{"val":"rgb(19, 114, 211)","hsl":{"h":210,"s":0.83,"l":0.45,"a":1}}},"gradients":[]}}]}__CONFIG_colors_palette__</div>
					
					<a href="#" class="tcb-button-link tve-form-button-submit tcb-plain-text" style=""><span class="tcb-button-icon" style="">
	<div class="tcb-clear" data-css="tve-u-11620b8f4fda33d"><div class="thrv_wrapper thrv_icon tve_no_drag tve_no_icons tcb-icon-inherit-style tcb-local-vars-root tcb-icon-display" data-tcb_hover_state_parent="" style="" data-selector="#lg-kz8c0yse .tve-form-button .thrv_icon"><svg class="tcb-icon" viewBox="0 0 24 24" data-id="icon-arrow_forward-duotone" data-name=""><path fill="none" d="M0 0h24v24H0V0z"></path><path d="M12 4l-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8-8-8z"></path></svg></div></div>
</span>

						<span class="tcb-button-texts" style=""><span class="tcb-button-text thrv-inline-text" style="">JOIN THE LIST</span></span>
					</a>
					<input type="submit" style="display: none !important;">
				</div>
			</div>
			<input id="_submit_option" type="hidden" name="_submit_option" value="redirect">
			<input id="_sendParams" type="hidden" name="_sendParams" value="1">
			<input id="_back_url" type="hidden" name="_back_url" value="#">
		<input type="hidden" id="tve_labels" name="tve_labels" value="YToyOntzOjQ6Im5hbWUiO3M6NDoiTmFtZSI7czo1OiJlbWFpbCI7czo1OiJFbWFpbCI7fQ=="><input type="hidden" id="tve_mapping" name="tve_mapping" value="YTowOnt9"></form>
	</div>
</div></div>
</div>