<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-15df11fe174"><div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb-resized tcb--cols--2"><div class="tcb-flex-col" data-css="tve-u-15df1235544" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption tcb-mobile-hidden" data-css="tve-u-15df122605f" style=""><span class="tve_image_frame"><img class="tve_image wp-image-2379" alt="" width="220" height="192" title="set02_widget_img" data-id="2379" src="{tve_leads_base_url}/images/set02_widget_img.png"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-15df1235553" style=""><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style=""><p data-default="Enter your text here..." data-css="tve-u-15df1261ae2"><span style="color: rgb(120, 172, 73); font-family: &quot;Open Sans&quot;; font-weight: 400; font-size: 32px;"><strong>GET INSTANT ACCESS</strong></span></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15df125b8a9"><p data-default="Enter your text here..." data-css="tve-u-15df1245bd8">to Our Awesome Product now!</p></div><div class="thrv_wrapper thrv_text_element" style=""><p data-default="Enter your text here..." data-css="tve-u-15df125190c">Duis sed odio sit amet nibh vulputate cursus a sit amet mauris aenean sollicitudin, lorem bibendum?</p></div></div></div></div></div><div class="thrv_wrapper thrv_lead_generation" data-connection="api" data-css="tve-u-15df1206d89"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--3 tcb-resized"><div class="tcb-flex-col" data-css="tve-u-15df126ca1e" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-15df1206d86">
<input type="text" data-field="name" name="name" placeholder="Your Name:" data-placeholder="Your Name:" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-15df126ca2f" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-15df1206d87">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Your Email:" data-placeholder="Your Email:" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-15df126ca3f" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-15df1206d88">
<button type="submit" style=""><span class="">Submit</span></button>
</div></div></div></div></div>
</div>
</form>
</div>
</div></div>