<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-15e1dbf3222"><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-15e1dc017b6"><div class="tcb-flex-row tcb--cols--2 tcb-resized tcb-mobile-edit" data-css="tve-u-15e1dc01ba1"><div class="tcb-flex-col" data-css="tve-u-15e1dbef601" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15e1dbed87c" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2428" alt="" width="165" height="165" title="set_28_icon" data-id="2428" src="{tve_leads_base_url}/images/set_28_icon.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-15e1dbef60b" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-15e1dc3843f"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e1dc06d8d"><p data-css="tve-u-15e1dbc91dc" data-default="Enter your text here...">Subscribe to our Newsletter!</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style=""><p data-css="tve-u-15e1dbd2dc2" data-default="Enter your text here...">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit ipsum, nec sagittis sem nibh id elit.</p></div></div></div></div></div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15e1dbfa718">
<div class="tve-content-box-background" data-css="tve-u-15e1dbf8579"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_lead_generation" data-connection="api" style="" data-css="tve-u-15e1dbfbd3e"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--2 tcb-resized"><div class="tcb-flex-col" data-css="tve-u-15e1dbc3a43" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-15e1dbdd239">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" class="" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-15e1dbc3a47" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-15e1dbe1f4e">
<button type="submit" class="tve-froala" style="">SUBSCRIBE</button>
</div></div></div></div></div>
</div>
<input type="hidden" name="__tcb_lg_fc" id="__tcb_lg_fc" value="YTowOnt9"></form>
</div>
</div></div>
</div></div>