<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" data-css="tve-u-05b44d48985a65"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15b44d48985aad">
<div class="tve-content-box-background" data-css="tve-u-25b44d48985aed"></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-35b44d48985b2b"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-45b44d48985b3b">
<div class="tve-content-box-background" data-css="tve-u-55b44d48985b7d"></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-65b44d48985bbc"><div class="thrv_wrapper thrv-columns" data-css="tve-u-75b44d48985c1d"><div class="tcb-flex-row v-2 tcb--cols--2" data-css="tve-u-85b44d48985c5a"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-95b44d48985c99">
<div class="tve-content-box-background" data-css="tve-u-105b44d48985cd7" data-clip-id="1zbsniy3ud1nw"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-right-1zbsniy3ud1nw" class="decoration-clip clip-path-right" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" pointer-width="8" pointer-height="4"><polygon points="0 0, 0 1, 0.96 1, 0.96 0.54, 1 0.5, 0.96 0.46, 0.96 0"></polygon></clipPath><clipPath id="clip-mobile-right-1zbsniy3ud1nw" class="decoration-clip clip-path-mobile-right" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="8" pointer-height="4" clip-path="url(#clip-mobile-bottom-1zbsniy3ud1nw)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-bottom-1zbsniy3ud1nw" class="decoration-clip clip-path-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="pointer" pointer-width="8" pointer-height="3" style=""><polygon points="0 0, 0 0.97, 0.46 0.97, 0.5 1, 0.54 0.97, 1 0.97, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-115b44d48985d30"><div class="thrv_wrapper thrv_heading" data-tag="h2" data-css="tve-u-125b44d48985d6e"><h2 style="text-align: left;" data-css="tve-u-135b44d48985dac"><strong>Get the Latest Investment News</strong></h2></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-145b44d48985de9"><p data-css="tve-u-155b44d48985e34" style="text-align: left;">Subscribe to our weekly newsletter to get the best deals straight in your inbox.</p></div></div>
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-165b44d48985e76" data-tcb_hover_state_parent="">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_2|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text">Yes, I Want to Stay Informed</span></span>
</a>
</div></div></div></div></div></div>
</div></div>
</div></div>