<div class="thrv-leads-screen-filler tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content tve_empty_dropzone" data-css="tve-u-05b44b5ff03700">
<div class="thrv_wrapper thrv-page-section" style="" data-css="tve-u-15b44b5ff03747">
<div class="tve-page-section-out"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-25b44b5ff037b2"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-35b44b5ff037f6">
<div class="tve-content-box-background" data-css="tve-u-45b44b5ff03843"></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-55b44b5ff0388a"><div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-65b44b5ff038d0" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<svg class="tcb-icon" viewBox="0 0 30 32" data-name="close"><path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path><path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path></svg>
</div><div class="thrv_wrapper thrv-columns" data-css="tve-u-75b44b5ff03910"><div class="tcb-flex-row v-2 tcb-medium-wrap tcb--cols--2" data-css="tve-u-85b44b5ff0394a"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-95b44b5ff0398e">
<div class="tve-content-box-background" data-css="tve-u-105b44b5ff039d3" data-clip-id="vrrg4joxgx989"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-right-vrrg4joxgx989" class="decoration-clip clip-path-right" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" pointer-width="8" pointer-height="4"><polygon points="0 0, 0 1, 0.96 1, 0.96 0.54, 1 0.5, 0.96 0.46, 0.96 0"></polygon></clipPath><clipPath id="clip-tablet-right-vrrg4joxgx989" class="decoration-clip clip-path-tablet-right" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="none" pointer-width="8" pointer-height="5" clip-path="url(#clip-tablet-bottom-vrrg4joxgx989)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-right-vrrg4joxgx989" class="decoration-clip clip-path-mobile-right" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="8" pointer-height="5" clip-path="url(#clip-mobile-bottom-vrrg4joxgx989)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-bottom-vrrg4joxgx989" class="decoration-clip clip-path-tablet-bottom" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="pointer" pointer-width="8" pointer-height="5" style=""><polygon points="0 0, 0 0.95, 0.46 0.95, 0.5 1, 0.54 0.95, 1 0.95, 1 0"></polygon></clipPath><clipPath id="clip-mobile-bottom-vrrg4joxgx989" class="decoration-clip clip-path-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="pointer" pointer-width="11" pointer-height="4" style=""><polygon points="0 0, 0 0.96, 0.445 0.96, 0.5 1, 0.555 0.96, 1 0.96, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-115b44b5ff03a28"><div class="thrv_wrapper thrv_heading" data-tag="h2" data-css="tve-u-125b44b5ff03a6a"><h2 style="text-align: left;" data-css="tve-u-135b44b5ff03aae"><strong>Get the Latest Investment News</strong></h2></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-145b44b5ff03af1"><p data-css="tve-u-155b44b5ff03b36" style="text-align: left;">Subscribe to our weekly newsletter to get the best deals straight in your inbox.</p></div></div>
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_lead_generation" data-connection="api" data-css="tve-u-165b44b5ff03b8b"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="tve_lg_input_container tve_lg_input" data-css="tve-u-175b44b5ff03bce" data-tcb_hover_state_parent="">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" class="">
</div>
<div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-185b44b5ff03c53" data-tcb_hover_state_parent="">
<button type="submit" class="tve-froala">Yes, I Want to Stay Informed</button>
</div>
</div>
<input id="_submit_option" type="hidden" name="_submit_option" value="message"><input id="__tcb_lg_msg" type="hidden" name="__tcb_lg_msg" value="YToyOntzOjU6ImVycm9yIjtzOjY6IkVycm9yISI7czo3OiJzdWNjZXNzIjtzOjg6IlN1Y2Nlc3MhIjt9"><input type="hidden" name="__tcb_lg_fc" id="__tcb_lg_fc" value="YTowOnt9"></form>
</div>
</div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-195b44b5ff03c99"><p data-css="tve-u-205b44b5ff03cdc" style="text-align: center;">By signing up you agree to <span data-css="tve-u-215b44b5ff03d1d" style="color: rgb(80, 127, 213);"><a href="" target="_blank"><u>our terms</u></a></span></p></div></div></div></div></div></div>
</div></div>
</div></div>