<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-0959ad920c16ec5"><div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb-resized tcb--cols--2"><div class="tcb-flex-col" data-css="tve-u-0959ad920c16f31" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption tcb-mobile-hidden" data-css="tve-u-0959ad920c16fa5" style=""><span class="tve_image_frame"><img class="tve_image wp-image-2379" alt="" width="220" height="192" title="set02_widget_img" data-id="2379" src="{tve_leads_base_url}/images/set02_widget_img.png"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-0959ad920c17001" style=""><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style=""><p data-default="Enter your text here..." data-css="tve-u-0959ad920c1705e"><span style="color: rgb(120, 172, 73); font-family: &quot;Open Sans&quot;; font-weight: 400; font-size: 32px;"><strong>GET INSTANT ACCESS</strong></span></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-0959ad920c170be"><p data-default="Enter your text here..." data-css="tve-u-0959ad920c17123">to Our Awesome Product now!</p></div><div class="thrv_wrapper thrv_text_element" style=""><p data-default="Enter your text here..." data-css="tve-u-0959ad920c17191">Duis sed odio sit amet nibh vulputate cursus a sit amet mauris aenean sollicitudin, lorem bibendum?</p></div></div></div></div></div><div class="thrv_wrapper thrv_lead_generation" data-connection="api" data-css="tve-u-0959ad920c171f1"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--3 tcb-resized"><div class="tcb-flex-col" data-css="tve-u-0959ad920c17252" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-0959ad920c172b1">
<input type="text" data-field="name" name="name" placeholder="Your Name:" data-placeholder="Your Name:" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-0959ad920c17316" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-159ad920c17374">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Your Email:" data-placeholder="Your Email:" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-159ad920c173d4" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-159ad920c17433">
<button type="submit" style=""><span class="">Submit</span></button>
</div></div></div></div></div>
</div>
</form>
</div>
</div></div>