<div class="thrv-ribbon tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content tve_empty_dropzone" data-css="tve-u-05b44bfabe9c6a">
<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-15b44bfabe9caf" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<svg class="tcb-icon" viewBox="0 0 30 32" data-name="close">
<path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path>
<path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path>
</svg>
</div>
<div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-25b44bfabe9d27">
<div class="tve-content-box-background" data-css="tve-u-35b44bfabe9d75"></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-45b44bfabe9dc2"><div class="thrv_wrapper thrv-columns" data-css="tve-u-55b44bfabe9e10"><div class="tcb-flex-row tcb--cols--2" data-css="tve-u-65b44bfabe9e55"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone" data-css="tve-u-75b44bfabe9e9f"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-85b44bfabe9eee" data-float="1">
<div class="tve-content-box-background" data-css="tve-u-95b44bfabe9f32" data-clip-id="aakymovv1tjhe"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-right-aakymovv1tjhe" class="decoration-clip clip-path-right" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" pointer-width="26" pointer-height="2"><polygon points="0 0, 0 1, 0.98 1, 0.98 0.63, 1 0.5, 0.98 0.37, 0.98 0"></polygon></clipPath><clipPath id="clip-mobile-right-aakymovv1tjhe" class="decoration-clip clip-path-mobile-right" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="14.000000000000002" pointer-height="4" clip-path="url(#clip-mobile-bottom-aakymovv1tjhe)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-right-aakymovv1tjhe" class="decoration-clip clip-path-tablet-right" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="pointer" pointer-width="17" pointer-height="3"><polygon points="0 0, 0 1, 0.97 1, 0.97 0.585, 1 0.5, 0.97 0.415, 0.97 0"></polygon></clipPath><clipPath id="clip-tablet-mobile-right-aakymovv1tjhe" class="decoration-clip clip-path-tablet-mobile-right" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="pointer" pointer-width="14.000000000000002" pointer-height="4"><polygon points="0 0, 0 1, 0.96 1, 0.96 0.5700000000000001, 1 0.5, 0.96 0.43, 0.96 0"></polygon></clipPath><clipPath id="clip-mobile-bottom-aakymovv1tjhe" class="decoration-clip clip-path-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="pointer" pointer-width="8" pointer-height="3" style=""><polygon points="0 0, 0 0.97, 0.46 0.97, 0.5 1, 0.54 0.97, 1 0.97, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-105b44bfabe9f76"><div class="thrv_wrapper thrv_heading" data-tag="h2" data-css="tve-u-115b44bfabe9fbd"><h2 data-css="tve-u-125b44bfabea01d" style="text-align: left;"><strong>Get the Latest Investment News</strong></h2></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-135b44bfabea066"><p data-css="tve-u-145b44bfabea0a5" style="text-align: left;">Subscribe to our weekly newsletter to get the best deals straight in your inbox.</p></div></div>
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-155b44bfabea0f2" data-tcb_hover_state_parent="">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_2|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text">Yes, I Want to Stay Informed</span></span>
</a>
</div></div></div></div></div></div>
</div></div>