<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-1600c7c3192" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__" style=""><svg class="tcb-icon" viewBox="0 0 30 32" data-name="close">
<path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path>
<path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path>
</svg></div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15e9edc9638">
<div class="tve-content-box-background"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15e9edb0076">
<div class="tve-content-box-background" data-css="tve-u-15e9edab125"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e05cb648f"><p data-css="tve-u-15e05ca4188" style="text-align: center;">Get Our <strong><span style="color: rgb(220, 69, 57);">Free Guides</span></strong> to Become a Happier, More Productive You!</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e05ccfc50"><p data-css="tve-u-15e05cc0ede" style="text-align: center;">Pick the guide you want to start with, to get your instant download:</p></div></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15e05cde313">
<div class="tve-content-box-background" data-css="tve-u-15e05ce0baf" data-clip-id="990dd043cc562"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-bottom-990dd043cc562" class="decoration-clip clip-path-bottom" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" pointer-width="100" pointer-height="100" style=""><polygon points="0 0, 0 0, 0 0, 0.5 1, 1 0, 1 0, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb" data-css="tve-u-15e05ce5165"></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15e9edbd9d4">
<div class="tve-content-box-background"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-15e05d7faf4"><div class="tcb-flex-row tcb--cols--3 tcb-medium-no-wrap" data-css="tve-u-15e05cf26a6"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15e05d01ba9" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2490" alt="" width="124" height="172" title="twelve_set_icon1" data-id="2490" src="{tve_leads_base_url}/images/twelve_set_icon1.png" style="width: 100%;"></span></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-1600c86ba48"><p data-css="tve-u-1600c855149" style="text-align: center;"><strong>Uncluttering 101</strong></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e05e12e6f"><p data-css="tve-u-1600c857178" style="text-align: center;">Pick the guide you want to start with, to get your instant download:</p></div><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-15e05e022c0">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_2|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-1600c858661"><span data-css="tve-u-1600c858675" style="font-family: Roboto; font-weight: 300;"><strong>Download Now</strong></span></span></span>
</a>
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15e05d6d61d" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2491" alt="" width="124" height="172" title="twelve_set_icon2" data-id="2491" src="{tve_leads_base_url}/images/twelve_set_icon2.png" style="width: 100%;"></span></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-1600c869bf3"><p data-css="tve-u-1600c859657" style="text-align: center;"><strong>Morning Kickstart</strong></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e05e194f7"><p data-css="tve-u-1600c85a7f9" style="text-align: center;">Learn how to adopt the morning routines of the world's most productive people.</p></div><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-15e05d20336">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_3|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-1600c85bbcf"><span data-css="tve-u-1600c85bbe1" style="font-family: Roboto; font-weight: 300;"><strong>Download Now</strong></span></span></span>
</a>
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15e05d73e2b" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2492" alt="" width="124" height="172" title="twelve_set_icon3" data-id="2492" src="{tve_leads_base_url}/images/twelve_set_icon3.png" style="width: 100%;"></span></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-1600c867a6a"><p data-css="tve-u-15e05d0db8d" style="text-align: center;"><strong>The Focus Key<em>​</em>​​​​</strong></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e05d1efd4"><p data-css="tve-u-15e05d16b6b" style="text-align: center;">The strategy for discovering what you're best at and doing more of it.</p></div><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-15e05d20336">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_4|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-1600c85f0e5"><span data-css="tve-u-1600c85f0f7" style="font-family: Roboto; font-weight: 300;"><strong>Download Now</strong></span></span></span>
</a>
</div></div></div></div></div></div>
</div></div>
</div>