<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-15d9e95bd96" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__" style="">
<svg class="tcb-icon" viewBox="0 0 30 32" data-name="close">
<path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path>
<path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path>
</svg>
</div>
<div class="thrv_wrapper thrv-page-section" style="" data-css="tve-u-1600b0dc10c">
<div class="tve-page-section-out"></div>
<div class="tve-page-section-in tve_empty_dropzone"><div class="thrv_wrapper thrv_heading" style="" data-css="tve-u-1600b0d1658"><h1 data-css="tve-u-15de9f3b637" style="text-align: center;">Your Website Analytics Are <strong><span style="color: rgb(185, 69, 69);">Useless.</span></strong></h1></div><div class="thrv_wrapper thrv-columns" data-css="tve-u-15de9fccd76" style=""><div class="tcb-flex-row tcb--cols--2 tcb-resized" data-css="tve-u-15de9fcd697"><div class="tcb-flex-col" data-css="tve-u-15de9f5ef2f" style=""><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper tve_image_caption tcb-mobile-hidden" data-css="tve-u-15de9f5e408" style=""><span class="tve_image_frame"><img class="tve_image wp-image-2390" alt="" width="322" height="330" title="set2_multistep_book" data-id="2390" src="{tve_leads_base_url}/images/set2_multistep_book.png"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-15de9f5ef41" style=""><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-15de9f63b13" style=""><p data-css="tve-u-15dea10cf5a"><strong>90% of online businesses use web analytics as a fancy distraction, collect the wrong data or fail to take intelligent action based on their anayltics. Or all of the above.</strong></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-1600b0d3185"><p data-css="tve-u-15dea10e832"><strong>Get our free whitepaper to fix the problem and join the top 10% of businesses.</strong></p></div></div></div></div></div><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-15de9f7c4cd">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_2|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-15dea111838">Yes, Send Me the Whitepaper</span></span>
</a>
</div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone tve_ea_thrive_leads_form_close" style="" data-css="tve-u-1600b0d5eed"><p data-css="tve-u-15de9f4fd2c" style="text-align: center;"><span style="color: rgb(153, 153, 153);"><a class="tve_evt_manager_listen tve_et_click" data-css="tve-u-1600b0c16d3" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;,&quot;config&quot;:{&quot;a&quot;:&quot;instant&quot;}}]_TNEVE_BCT__" href="javascript%3Avoid(0)"><strong><u>No thanks, I’d like to stay in the dark.</u></strong></a></span></p></div></div>
</div>