<div class="thrv-ribbon tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content tve_empty_dropzone" data-css="tve-u-05b44bfbd9ce1d">
<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-15b44bfbd9ce5b" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<svg class="tcb-icon" viewBox="0 0 30 32" data-name="close">
<path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path>
<path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path>
</svg>
</div>
<div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-25b44bfbd9cea9">
<div class="tve-content-box-background" data-css="tve-u-35b44bfbd9cef2"></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-45b44bfbd9cf36"><div class="thrv_wrapper thrv-columns" data-css="tve-u-55b44bfbd9cf7c"><div class="tcb-flex-row tcb--cols--2" data-css="tve-u-65b44bfbd9cfc0"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone" data-css="tve-u-75b44bfbd9d004"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-85b44bfbd9d048" data-float="1">
<div class="tve-content-box-background" data-css="tve-u-95b44bfbd9d08d" data-clip-id="8migre2lpyk3k"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-right-8migre2lpyk3k" class="decoration-clip clip-path-right" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" pointer-width="26" pointer-height="2"><polygon points="0 0, 0 1, 0.98 1, 0.98 0.63, 1 0.5, 0.98 0.37, 0.98 0"></polygon></clipPath><clipPath id="clip-mobile-right-8migre2lpyk3k" class="decoration-clip clip-path-mobile-right" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="14.000000000000002" pointer-height="4" clip-path="url(#clip-mobile-bottom-8migre2lpyk3k)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-right-8migre2lpyk3k" class="decoration-clip clip-path-tablet-right" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="pointer" pointer-width="17" pointer-height="3"><polygon points="0 0, 0 1, 0.97 1, 0.97 0.585, 1 0.5, 0.97 0.415, 0.97 0"></polygon></clipPath><clipPath id="clip-tablet-mobile-right-8migre2lpyk3k" class="decoration-clip clip-path-tablet-mobile-right" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="pointer" pointer-width="14.000000000000002" pointer-height="4"><polygon points="0 0, 0 1, 0.96 1, 0.96 0.5700000000000001, 1 0.5, 0.96 0.43, 0.96 0"></polygon></clipPath><clipPath id="clip-mobile-bottom-8migre2lpyk3k" class="decoration-clip clip-path-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="pointer" pointer-width="8" pointer-height="4" style=""><polygon points="0 0, 0 0.96, 0.46 0.96, 0.5 1, 0.54 0.96, 1 0.96, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-105b44bfbd9d0d2"><div class="thrv_wrapper thrv_heading" data-tag="h2" data-css="tve-u-115b44bfbd9d116"><h2 data-css="tve-u-125b44bfbd9d15b" style="text-align: left;"><strong>Get the Latest Investment News</strong></h2></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-135b44bfbd9d1a9"><p data-css="tve-u-145b44bfbd9d1f0" style="text-align: left;">Subscribe to our weekly newsletter to get the best deals straight in your inbox.</p></div></div>
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_lead_generation" data-connection="api" data-css="tve-u-155b44bfbd9d236"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--2 tcb-resized" data-css="tve-u-165b44bfbd9d275"><div class="tcb-flex-col" data-css="tve-u-175b44bfbd9d2b7" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-185b44bfbd9d30f" data-tcb_hover_state_parent="">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" class="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-195b44bfbd9d353" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-205b44bfbd9d397" data-tcb_hover_state_parent="">
<button type="submit" class="tve-froala">Yes, I Want to Stay Informed</button>
</div></div></div></div></div>
</div>
<input id="_submit_option" type="hidden" name="_submit_option" value="message"><input id="__tcb_lg_msg" type="hidden" name="__tcb_lg_msg" value="YToyOntzOjU6ImVycm9yIjtzOjY6IkVycm9yISI7czo3OiJzdWNjZXNzIjtzOjg6IlN1Y2Nlc3MhIjt9"><input type="hidden" name="__tcb_lg_fc" id="__tcb_lg_fc" value="YTowOnt9"></form>
</div>
</div></div></div></div></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-215b44bfbd9d3da"><p data-css="tve-u-225b44bfbd9d41e" style="text-align: right;">By signing up you agree to <span data-css="tve-u-235b44bfbd9d463" style="color: rgb(80, 127, 213);"><a href="" target="_blank"><u>our terms</u></a></span></p></div></div>
</div></div>