<div class="thrv_wrapper thrv-page-section" data-css="tve-u-17fc0c511e6">
<div class="tve-page-section-out" data-css="tve-u-17fc0c511e8" data-clip-id="rm0w3fw2hdo6c"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-17fc0c511e9"><div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-17fc0c511ea" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__" data-float="1" data-tcb_hover_state_parent="">
<svg class="tcb-icon" viewBox="0 0 30 32" data-name="close">
<path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path>
<path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path>
</svg>
</div><div class="thrv_wrapper thrv-columns" data-css="tve-u-17fc0c511ec" style="--tcb-col-el-width:650;"><div class="tcb-flex-row tcb-resized tcb--cols--2 v-2" data-css="tve-u-17fc0c511ed"><div class="tcb-flex-col c-33" data-css="tve-u-17fc0c511ee" style=""><div class="tcb-col tve_empty_dropzone" data-css="tve-u-17fc0c511f0"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-17fc0c511f1">
<div class="tve-content-box-background" data-css="tve-u-17fc0c511f2" data-clip-id="zv6vt97fid346"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-17fc0c511f3"><div class="thrv_wrapper thrv_text_element" data-tag="h2" data-css="tve-u-17fc0c511f5"><h2 data-css="tve-u-17fc0c511f6" style="text-align: center;" class="">50<br>%</h2></div><div class="thrv_wrapper thrv_text_element" data-tag="h2" data-css="tve-u-17fc0c511f7" data-float="1"><h2 data-css="tve-u-17fc0c511f8" class="">Off</h2></div></div>
</div></div></div><div class="tcb-flex-col c-66" data-css="tve-u-17fc0c511fa" style=""><div class="tcb-col tve_empty_dropzone" data-css="tve-u-17fc0c511fb"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-17fc0c511fc" data-float="1">
<div class="tve-content-box-background" data-css="tve-u-17fc0c511fd" data-clip-id="j8rtvifveibal"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-left-j8rtvifveibal" class="decoration-clip clip-path-left" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="divider" pointer-width="11" pointer-height="10" style="zigzag" clip-path="url(#clip-top-j8rtvifveibal)"><polygon points="0.1 0, 0.1 0.05, 0.1 0.05, 0 0.10277800000000001, 0.1 0.155556, 0 0.20833400000000002, 0.1 0.261112, 0 0.31389, 0.1 0.366668, 0 0.419446, 0.1 0.472224, 0 0.525002, 0.1 0.5777800000000001, 0 0.6305580000000001, 0.1 0.683336, 0 0.736114, 0.1 0.788892, 0 0.84167, 0.1 0.894448, 0 0.947226, 0.1 1.000004, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-left-j8rtvifveibal" class="decoration-clip clip-path-mobile-left" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="0" pointer-height="0" style="zigzag" clip-path="url(#clip-top-j8rtvifveibal)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-top-j8rtvifveibal" class="decoration-clip clip-path-top" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="none" pointer-width="5" pointer-height="5" style="zigzag"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-left-j8rtvifveibal" class="decoration-clip clip-path-mobile-left" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="11" pointer-height="10" style="zigzag" clip-path="url(#clip-mobile-top-j8rtvifveibal)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-mobile-left-j8rtvifveibal" class="decoration-clip clip-path-mobile-mobile-left" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="11" pointer-height="10" style="zigzag" clip-path="url(#clip-mobile-top-j8rtvifveibal)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-top-j8rtvifveibal" class="decoration-clip clip-path-mobile-top" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" pointer-width="47" pointer-height="33" style="curves"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon><ellipse cx="0.25" cy="0.33" rx="0.250000" ry="0.33"></ellipse><ellipse cx="0.75" cy="0.33" rx="0.250000" ry="0.33"></ellipse></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-17fc0c511ff"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-17fc0c51200"><p data-css="tve-u-17fc0c51201" style="text-align: center;">Great! Just subscribe to our newsletter and get this offer!</p></div><div class="thrv_wrapper thrv_lead_generation" data-connection="api" data-css="tve-u-17fc0c51203" data-settings-id="tve-form-17fc0c5ea64" data-form-settings="__TCB_FORM__{&quot;v&quot;:1,&quot;apis&quot;:[],&quot;extra&quot;:{},&quot;captcha&quot;:0,&quot;custom_tags&quot;:{},&quot;inputs&quot;:{&quot;email&quot;:{&quot;id&quot;:&quot;email&quot;,&quot;label&quot;:&quot;email&quot;,&quot;type&quot;:&quot;email&quot;},&quot;undefined&quot;:{}},&quot;form_identifier&quot;:&quot;post-footer-form-b2lqdd&quot;,&quot;form_type&quot;:&quot;lead_generation&quot;}__TCB_FORM__"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate" autocomplete="new-password">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="tve_lg_input_container tve_lg_input" data-css="tve-u-17fc0c51204" data-tcb_hover_state_parent="">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" class="">
</div>
<div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-17fc0c51205" data-tcb_hover_state_parent="">
<button type="submit" class="tve-froala">Get your discount</button>
</div>
</div>
<input id="_submit_option" type="hidden" name="_submit_option" value="reload"><input id="_back_url" type="hidden" name="_back_url" value=""><input id="_autofill" type="hidden" name="_autofill" value=""></form>
</div>
</div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-17fc0c51207"><p data-css="tve-u-17fc0c51208" style="text-align: center;">By subscribing you agree to our <span data-css="tve-u-17fc0c51209" style="color: rgb(126, 127, 132);"><a href="" target="_blank"><u>terms &amp; conditions</u></a></span></p></div></div>
</div></div></div></div></div></div>
</div>